# Generated by Django 5.2.17 on 2026-09-12 15:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tool_name', models.CharField(max_length=100)),
                ('category_title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('tool_logo_url', models.URLField(blank=True, null=True)),
                ('sub_skills', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
