# Generated by Django 5.2.17 on 2026-09-20 12:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=255)),
                ('start_year', models.IntegerField()),
                ('end_year', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
